# Standards: 2.1.0
---

# 4.1.3 Ensure auditing for processes that start prior to auditd is enabled
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "4.1.2"
    - scored
- name: 4.1.3 - Ensure auditing for processes that start prior to auditd is enabled
  lineinfile:
    regexp: "^GRUB_CMDLINE_LINUX="
    line: 'GRUB_CMDLINE_LINUX="console=ttyS0,115200n8 console=tty0 net.ifnames=0 crashkernel=auto audit=1"'
    state: present
    dest: "/etc/default/grub"
    backup: yes
  tags:
    - level-2
    - section-4
    - "4.1.3"
    - scored

- name: 4.1.3 - Run the command to update the Grub Configuration
  command: "grub2-mkconfig > /boot/grub2/grub.cfg"
  changed_when: false
  tags:
    - level-2
    - section-4
    - "4.1.3"
    - scored
