# Standards: 2.1.0
---
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "1.1.4"
    - scored
  
# 1.1.4 Ensure nosuid option set on /tmp partition

- name: 1.1.4 - Ensure nosuid option set on /tmp partition
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nosuid']) | join(',') }}"
  when: item.mount == '/tmp'
  with_items: "{{ ansible_mounts }}"
  register: action_1_1_4
  tags:
    - level-1
    - section-1
    - "1.1.4"
    - scored

- name: Logging ansible action for - 1.1.4
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.1.3 : remount /tmp with nosuid and update fstab"
  when: action_1_1_4 is defined and action_1_1_4.changed

  tags:
    - level-1
    - section-1
    - "1.1.4"
    - scored

