# Standards: 2.1.0
---
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "1.1.17"
    - scored

# 1.1.17 Ensure noexec option set on /dev/shm partition
- include: all_mounts_facts.yml
  tags:
    - level-1
    - section-1
    - "1.1.17"
    - scored

- name: 1.1.17 - Ensure noexec option set on /dev/shm partition
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['noexec']) | join(',') }}"
  when: item.mount == '/dev/shm'
  with_items: "{{ all_mounts.stdout | default('{}') | from_json }}"
  register: action_1_1_17

  tags:
    - level-1
    - section-1
    - "1.1.17"
    - scored
  
- name: Logging ansible action for - 1.1.17
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.1.17 : remount /dev/shm with noexec and update fstab"
  when: action_1_1_17 is defined and action_1_1_17.changed

  tags:
    - level-1
    - section-1
    - "1.1.17"
    - scored

