# Standards: 2.1.0
---
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "1.1.3"
    - scored
  
# 1.1.3 Ensure nodev option set on /tmp partition

- name: 1.1.3 - Ensure nodev option set on /tmp partition
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nodev']) | join(',') }}"
  when: item.mount == '/tmp'
  with_items: "{{ ansible_mounts }}"
  register: action_1_1_3
  tags:
    - level-1
    - section-1
    - "1.1.3"
    - scored
  
- name: Logging ansible action for - 1.1.3
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.1.3 : remount /tmp with nodev and update fstab"
  when: action_1_1_3 is defined and action_1_1_3.changed

  tags:
    - level-1
    - section-1
    - "1.1.3"
    - scored

