# Standards: 2.1.0
---
#########
# Originally it was using file glob which will not work on remote fs.
# Hence using find module to loop over *.repo to check gpgcheck
########
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "1.2.3"
    - scored

- name: 1.2.3 - Prepare the file list on the remote machine
  find:
    paths: /etc/yum.repos.d/
    patterns: "*.repo"
  register: file_list
  changed_when: False
  tags:
    - level-1
    - "1.2.3"
    - scored

- name: 1.2.3 - Display the list of files to be modified
  debug:
    msg: File to be modified {{ item.path }}
  with_items: "{{ file_list.files }}"
  changed_when: False
  tags:
    - level-1
    - "1.2.3"
    - scored

# 1.2.3 - Ensure gpgcheck is globally activated

- name: 1.2.3 - Verify that gpgcheck is enabled in /etc/yum.conf
  lineinfile:
    regexp: "^gpgcheck"
    line: "gpgcheck=1"
    dest: "/etc/yum.conf"
  register: action_1_2_3_01
  tags:
    - level-1
    - "1.2.3"
    - scored

- name: 1.2.3 - Verify that gpgcheck is enabled for all repositories in /etc/yum.repos.d
  replace:
    regexp: "^gpgcheck=0"
    replace: "gpgcheck=1"
    dest: "{{ item.path }}"  
  with_items: "{{ file_list.files }}"
  register: action_1_2_3_02
  tags:
    - level-1
    - "1.2.3"
    - scored

- name: Logging ansible action for - 1.2.3 part01
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.2.3 : gpgcheck is enabled in /etc/yum.conf"
  when: action_1_2_3_01 is defined and action_1_2_3_01.changed

  tags:
    - level-1
    - section-1
    - "1.2.3"
    - scored

- name: Logging ansible action for - 1.2.3 part02
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.2.3 : gpgcheck is enabled in {{ item.path }}"
  with_items: "{{ file_list.files }}"
  when: action_1_2_3_02 is defined and action_1_2_3_02.changed

  tags:
    - level-1
    - section-1
    - "1.2.3"
    - scored
