# Standards: 2.1.0
---

- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "3.1.1"
    - scored

# 3.1.1 Ensure IP forwarding is disabled

- name: 3.1.1 - Ensure IP forwarding is disabled and updated in the active kernel too
  sysctl:
    name: net.ipv4.ip_forward
    ignoreerrors: yes
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes
  register: action_3_1_1
  notify: Flush ipv4 route
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored

- name: 3.1.1 - Logging action 'Ensure IP forwarding is disabled and updated in the active kernel too'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 3.1.1 : Execute 'sysctl -w net.ipv4.ip_forward=0 and sysctl -w net.ipv4.route.flush=1' and update /etc/sysctl.conf"
  when: action_3_1_1 is defined and action_3_1_1.changed
  tags:
    - level-1
    - "3.1.1"
    - scored