# Standards: 2.1.0
---

# 4.2.2.1 Ensure syslog-ng service is enabled

- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "4.2.2.1"
    - scored

- name: 4.2.2.1 - Check if syslog-ng is installed
  yum:
    name: syslog-ng
    state: present
  when: cis_enable_syslog_ng
  tags:
    - level-1
    - section-4
    - "4.2.2.1"
    - scored

- name: 4.2.2.1 - Ensure syslog-ng service is enabled
  service:
    name: "syslog-ng"
    enabled: true
    state: started
  when:
    - cis_enable_syslog_ng
    - syslog_ng_4_2_2_1.rc is not defined or syslog_ng_4_2_2_1.rc == 0
  register: action_4_2_2_1
  ignore_errors: false
  tags:
    - level-1
    - section-4
    - "4.2.2.1"
    - scored

- name: 4.2.2.1 - Logging Task 'Ensure syslog-ng service is enabled'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 4.2.2.1 : systemctl enable syslog-ng"
  when: action_4_2_2_1 is defined and action_4_2_2_1.changed 
  tags:
    - level-1
    - section-1
    - "4.2.2.1"
    - scored
