# Standards: 2.1.0
---

# 5.1.1 Ensure cron daemon is enabled
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "5.1.1"
    - scored

- name: 5.1.1 - Ensure cron is installed
  yum:
    name: cronie
    state: present
  tags:
    - level-1
    - section-5
    - "5.1.1"
    - scored

- name: 5.1.1 - Ensure cron daemon is enabled
  service:
    name: "crond"
    enabled: true
    state: started
  ignore_errors: false
  register: action_5_1_1
  tags:
    - level-1
    - section-5
    - "5.1.1"
    - scored

- name: 5.1.1 - Logging Task 'Ensure cron daemon is enabled'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 5.1.1 : systemctl enable crond"
  when: action_5_1_1 is defined and action_5_1_1.changed 
  tags:
    - level-1
    - section-1
    - "5.1.1"
    - scored