# Standards: 2.1.0
---

# 5.1.6 Ensure permissions on /etc/cron.monthly are configured
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "5.1.6"
    - scored

- name: 5.1.6 - Ensure permissions on /etc/cron.monthly are configured
  file:
    path: "/etc/cron.monthly"
    owner: root
    group: root
    mode: '0600'
  register: action_5_1_6
  tags:
    - level-1
    - section-6
    - "5.1.6"
    - scored

- name: 5.1.6 - Logging Task 'Ensure permissions on /etc/cron.monthly are configured'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 5.1.6 : chown root:root /etc/cron.monthly && chmod og-rwx /etc/cron.monthly"
  when: action_5_1_6 is defined and action_5_1_6.changed 
  tags:
    - level-1
    - section-1
    - "5.1.6"
    - scored