# Standards: 2.1.0
---

# 5.1.5 Ensure permissions on /etc/cron.weekly are configured
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "5.1.5"
    - scored


- name: 5.1.5 - Ensure permissions on /etc/cron.weekly are configured
  file:
    path: "/etc/cron.weekly"
    owner: root
    group: root
    mode: '0600'
  register: action_5_1_5
  tags:
    - level-1
    - section-5
    - "5.1.5"
    - scored

- name: 5.1.5 - Logging Task 'Ensure permissions on /etc/cron.weekly are configured'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 5.1.5 : chown root:root /etc/cron.weekly && chmod og-rwx /etc/cron.weekly"
  when: action_5_1_5 is defined and action_5_1_5.changed 
  tags:
    - level-1
    - section-1
    - "5.1.5"
    - scored