# Standards: 2.1.0
---

# 5.2.1 Ensure permissions on /etc/ssh/sshd_config are configured
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "5.2.1"
    - scored

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.1"
    - scored

- name: 5.2.1 - Ensure permissions on /etc/ssh/sshd_config are configured
  file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
  when: sshd_config.stat.exists
  register: action_5_2_1
  tags:
    - level-1
    - section-5
    - "5.2.1"
    - scored

- name: 5.2.1 - Logging Task 'Ensure permissions on /etc/ssh/sshd_config are configured'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 5.2.1 : 'chown root:root /etc/ssh/sshd_config  && chmod og-rwx /etc/ssh/sshd_config'"
  when: action_5_2_1 is defined and action_5_2_1.changed 
  tags:
    - level-1
    - section-1
    - "5.2.1"
    - scored