# Standards: 2.1.0
---
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "6.1.5"
    - scored

# 6.1.5 Ensure permissions on /etc/gshadow are configured

- name: 6.1.5 - Ensure permissions on /etc/gshadow are configured
  file:
    path: /etc/gshadow
    owner: root
    group: root
    mode: '0000'
  register: action_6_1_5
  tags:
    - level-1
    - section-6
    - "6.1.5"
    - scored

- name: '6.1.5 - Logging action - Ensure permissions on /etc/gshadow are configured'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 6.1.5 : 'chown root:root /etc/gshadow && chmod 000 /etc/gshadow'"
  when: action_6_1_5 is defined and action_6_1_5.changed
  
  tags:
    - level-1
    - "6.1.5"
    - scored