# Standards: 2.1.0
---
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "6.2.3"
    - scored

# 6.2.3 Ensure no legacy "+" entries exist in /etc/shadow

- name: 6.2.3 - Ensure no legacy "+" entries exist in /etc/shadow
  replace:
    dest: "/etc/shadow"
    regexp: "^\\+:.*\n"
  register: action_6_2_3
  tags:
    - level-1
    - section-6
    - "6.2.3"
    - scored


- name: '6.2.3 - Logging action - Ensure no legacy "+" entries exist in /etc/shadow'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 6.2.3 : Ensure no legacy '+' entries exist in /etc/shadow"
  when: action_6_2_3 is defined and action_6_2_3.changed
  
  tags:
    - level-1
    - "6.2.3"
    - scored