# Standards: 2.1.0
---

# 1.1.15 Ensure nodev option set on /dev/shm partition

#######################################################################
# normally nodev set on /dev/shm and it is not mounted via fstab.
# hence I do not see this info in ansible_mounts
#
#######################################################################
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "1.1.15"
    - scored

# Adding custom facter script
- include: all_mounts_facts.yml
  tags:
    - level-1
    - section-1
    - "1.1.15"
    - scored

- name: 1.1.15 - Ensure nodev option set on /dev/shm partition
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nodev']) | join(',') }}"
  when: item.mount == '/dev/shm'
  with_items: "{{ all_mounts.stdout | default('{}') | from_json }}"
  register: action_1_1_15
  tags:
    - level-1
    - section-1
    - "1.1.15"
    - scored

- name: Logging ansible action for 1.1.14
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.1.14 : remount /dev/shm with nodev and update fstab"
  when: action_1_1_15 is defined and action_1_1_15.changed

  tags:
    - level-1
    - section-1
    - "1.1.15"
    - scored
