# Standards: 2.1.0
---

# Include date, time and process id finder
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "1.1.1.4"
    - scored

# 1.1.1.4 - Ensure mounting of hfs filesystems is disabled

- name: 1.1.1.4 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_1_1_1_4
  tags:
    - level-1
    - section-1
    - "1.1.1.4"
    - scored

- name: 1.1.1.4 - Ensure mounting of hfs filesystems is disabled
  copy:
    dest: "{{ cis_modprobe_conf_filename }}"
    content: "install hfs /bin/true\n"
  when: modprobe_1_1_1_4.stat.exists is not defined or not modprobe_1_1_1_4.stat.exists
  register: action_1_1_1_4_01
  tags:
    - level-1
    - section-1
    - "1.1.1.4"
    - scored

- name: 1.1.1.4 - Ensure mounting of hfs filesystems is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install hfs\\s+"
    line: "install hfs /bin/true"
  when: modprobe_1_1_1_4.stat.exists is defined and modprobe_1_1_1_4.stat.exists
  register: action_1_1_1_4_02
  tags:
    - level-1
    - section-1
    - "1.1.1.4"
    - scored


- name: 1.1.1.4 - Ensure hfs module removed from the running kernel
  modprobe: 
    name: hfs
    state: absent
  register: action_1_1_1_4_03
  tags:
    - level-1
    - section-1
    - "1.1.1.4"
    - scored

- name: 1.1.1.4 - Logging Task 
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.1.1.4 : insert install hfs /bin/true into {{ cis_modprobe_conf_filename }}"
  when: action_1_1_1_4_01 is defined and action_1_1_1_4_01.changed  
  tags:
    - level-1
    - section-1
    - "1.1.1.4"
    - scored

- name: 1.1.1.4 - Logging Task
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 1.1.1.4 : Append  {{ cis_modprobe_conf_filename }} with content 'install hfs /bin/true'"
  when: action_1_1_1_4_02 is defined and action_1_1_1_4_02.changed 
  
  tags:
    - level-1
    - section-1
    - "1.1.1.4"
    - scored

- name: 1.1.1.4 - Logging Task
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 1.1.1.4 : 'execute rmmod hfs'"
  when: action_1_1_1_4_03 is defined and action_1_1_1_4_03.changed 
  
  tags:
    - level-1
    - section-1
    - "1.1.1.4"
    - scored

