# Standards: 2.1.0
---
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "1.1.1.8"
    - scored

# 1.1.1.8 - Ensure mounting of FAT filesystems is disabled

- name: 1.1.1.8 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_1_1_1_8
  tags:
    - level-1
    - section-1
    - "1.1.1.8"
    - scored

- name: 1.1.1.8 - Ensure mounting of vfat filesystems is disabled
  copy:
    dest: "{{ cis_modprobe_conf_filename }}"
    content: "install vfat /bin/true\n"
  when: modprobe_1_1_1_8.stat.exists is not defined or not modprobe_1_1_1_8.stat.exists
  register: action_1_1_1_8_01
  tags:
    - level-1
    - section-1
    - "1.1.1.8"
    - scored

- name: 1.1.1.8 - Ensure mounting of vfat filesystems is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install vfat"
    line: "install vfat /bin/true"
  when: modprobe_1_1_1_8.stat.exists is defined and modprobe_1_1_1_8.stat.exists
  register: action_1_1_1_8_02
  tags:
    - level-1
    - section-1
    - "1.1.1.8"
    - scored

- name: 1.1.1.8 - Ensure vfat module is removed from kernel
  modprobe:
    name: vfat
    state: absent
  register: action_1_1_1_8_03
  
  tags:
    - level-1
    - section-1
    - "1.1.1.8"
    - scored

- name: 1.1.1.8 - Logging Task 
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.1.1.8 : insert install vfat /bin/true into {{ cis_modprobe_conf_filename }}"
  when: action_1_1_1_8_01 is defined and action_1_1_1_8_01.changed 

  tags:
    - level-1
    - section-1
    - "1.1.1.8"
    - scored

- name: 1.1.1.8 - Logging Task 
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.1.1.8 : Append install vfat /bin/true into {{ cis_modprobe_conf_filename }}"
  when: action_1_1_1_8_02 is defined and action_1_1_1_8_02.changed 

  tags:
    - level-1
    - section-1
    - "1.1.1.8"
    - scored


- name: 1.1.1.8 - Logging Task 
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.1.1.8 : Execute 'rmmod vfat'"
  when: action_1_1_1_8_03 is defined and action_1_1_1_8_03.changed 

  tags:
    - level-1
    - section-1
    - "1.1.1.8"
    - scored