# Standards: 2.1.0
---
#########
# Originally it was using file glob which will not work on remote fs.
# Hence using find module to loop over *.repo to check gpgcheck
########

- name: 1.2.3 - Prepare the file list on the remote machine
  find:
    paths: /etc/yum.repos.d/
    patterns: "*.repo"
  register: file_list
  changed_when: False
  tags:
    - level-1
    - "1.2.3"
    - scored

- name: 1.2.3 - Display the list of files to be modified
  debug:
    msg: File to be modified {{ item.path }}
  with_items: "{{ file_list.files }}"
  changed_when: False
  tags:
    - level-1
    - "1.2.3"
    - scored

# 1.2.3 - Ensure gpgcheck is globally activated

- name: 1.2.3 - Verify that gpgcheck is enabled in /etc/yum.conf
  lineinfile:
    regexp: "^gpgcheck"
    line: "gpgcheck=1"
    dest: "/etc/yum.conf"
  tags:
    - level-1
    - "1.2.3"
    - scored

- name: 1.2.3 - Verify that gpgcheck is enabled for all repositories in /etc/yum.repos.d
  replace:
    regexp: "^gpgcheck=0"
    replace: "gpgcheck=1"
    dest: "{{ item.path }}"  
  with_items: "{{ file_list.files }}"
  tags:
    - level-1
    - "1.2.3"
    - scored

