# Standards: 2.1.0
---
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "1.3.1"
    - scored

# 1.3.1 Ensure AIDE is installed

- name: 1.3.1 - Ensure AIDE is installed
  yum:
    name: aide
    state: present
  register: action_1_3_1_01
  tags:
    - level-1
    - section-1
    - "1.3.1"
    - scored

- name: 1.3.1 - Check that aide database exists
  stat:
    path: "{{ cis_aide_database_filename }}"
  register: action_1_3_1_02
  tags:
    - level-1
    - section-1
    - "1.3.1"
    - scored

# We expect that 'aide --init' has been run and the generated database has been moved
- name: 1.3.1 - Ensure aide database exists
  command: "{{ item }}"
  when: action_1_3_1_02.stat.exists is not defined or not action_1_3_1_02.stat.exists
  with_items:
    - "aide --init"
    - "mv {{ cis_aide_src_database_filename }} {{ cis_aide_database_filename }}"
  register: action_1_3_1_03
  tags:
    - level-1
    - section-1
    - "1.3.1"
    - scored

- name: 1.3.1 - Logging action
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.3.1 : Execute 'yum install aide'"
  when: action_1_3_1_01 is defined and action_1_3_1_01.changed  
  tags:
    - level-1
    - section-1
    - "1.3.1"
    - scored

- name: 1.3.1 - Logging action
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.3.1 : Execute 'aide --init'"
  when: action_1_3_1_03 is defined and action_1_3_1_03.changed  
  tags:
    - level-1
    - section-1
    - "1.3.1"
    - scored
