# Standards: 2.1.0
---
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "1.3.2"
    - scored
  
# 1.3.2 - Ensure filesystem integrity is regularly checked

- name: 1.3.2 - Create cron entry to run aide filesystem integrity check regularly
  cron:
    name: "CIS 1.3.2 - Run aide filesystem integrity check"
    user: "{{ cis_aide_cron_user }}"
    job: "{{ cis_aide_cron_job }}"
    minute: "{{ cis_aide_cron_minute }}"
    hour: "{{ cis_aide_cron_hour }}"
    weekday: "{{ cis_aide_cron_dow }}"
    day: "{{ cis_aide_cron_dom }}"
    month: "{{ cis_aide_cron_month }}"
    state: present
  register: action_1_3_2
  tags:
    - level-1
    - section-1
    - "1.3.2"
    - scored

- name: 1.3.2 - Logging action
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.3.2 : Added following line to root user crontab '0 5 * * * /usr/sbin/aide --check'"
  when: action_1_3_2 is defined and action_1_3_2.changed  
  tags:
    - level-1
    - section-1
    - "1.3.2"
    - scored
