# Standards: 0.11
---

# 1.4.3 - Ensure interactive boot is not enabled

- name: 1.4.3 - Check if sysconfig resuce file exists
  stat:
    path: "{{ cis_sysconfig_rescue_filename }}"
  register: sysconfig_rescue_1_4_3
  tags:
    - level-1
    - "1.4.3"
    - scored

- name: 1.4.3 - Check if sysconfig emergency file exists
  stat:
    path: "{{ cis_sysconfig_emergency_filename }}"
  register: sysconfig_emergency_1_4_3
  tags:
    - level-1
    - "1.4.3"
    - scored


- name: 1.4.3 - Ensure authentication enabled for single user mode - resuce
  command: grep "/sbin/sulogin" "{{ cis_sysconfig_rescue_filename }}"
  register: cis_rescue_1_4_3_output
  ignore_errors: True
  changed_when: False
  when: sysconfig_rescue_1_4_3 is defined and sysconfig_rescue_1_4_3.stat.exists
  tags:
    - level-1
    - "1.4.3"
    - scored

- name: 1.4.3 - Ensure authentication enabled for single user mode - emergency
  command: grep "/sbin/sulogin" "{{ cis_sysconfig_emergency_filename }}"
  register: cis_rescue_1_4_3_output
  ignore_errors: True
  changed_when: False
  when: sysconfig_emergency_1_4_3 is defined and sysconfig_emergency_1_4_3.stat.exists
  tags:
    - level-1
    - "1.4.3"
    - scored

- name: 1.4.3 - Ensure authentication enabled for single user mode - resuce
  lineinfile:
    dest: "{{ cis_sysconfig_rescue_filename }}"
    regexp: '^ExecStart='
    insertafter: '^ExecStartPre=\-\/bin\/echo '
    line: 'ExecStart=-/bin/sh -c \"/usr/sbin/sulogin; /usr/bin/systemctl --fail --no-block default"'
  when: 
    - sysconfig_rescue_1_4_3 is defined and sysconfig_rescue_1_4_3.stat.exists
    - cis_rescue_1_4_3_output != 0
  tags:
    - level-1
    - "1.4.3"
    - scored

- name: 1.4.3 - Ensure authentication enabled for single user mode - emergency
  lineinfile:
    dest: "{{ cis_sysconfig_emergency_filename }}"
    regexp: '^ExecStart='
    insertafter: '^ExecStartPre=\-\/bin\/echo '
    line: 'ExecStart=-/bin/sh -c "/usr/sbin/sulogin; /usr/bin/systemctl --fail --no-block default"'
  when: 
    - sysconfig_emergency_1_4_3 is defined and sysconfig_emergency_1_4_3.stat.exists
    - cis_rescue_1_4_3_output != 0
  tags:
    - level-1
    - "1.4.3"
    - scored
