# Standards: 0.11
---

- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "1.4.3"
    - scored
  
# 1.4.3 - Ensure interactive boot is not enabled

- name: 1.4.3 - Check if sysconfig resuce file exists
  stat:
    path: "{{ cis_sysconfig_rescue_filename }}"
  register: sysconfig_rescue_1_4_3
  tags:
    - level-1
    - "1.4.3"
    - scored

- name: 1.4.3 - Check if sysconfig emergency file exists
  stat:
    path: "{{ cis_sysconfig_emergency_filename }}"
  register: sysconfig_emergency_1_4_3
  tags:
    - level-1
    - "1.4.3"
    - scored


- name: '1.4.3 - Ensure authentication enabled for single user mode - resuce'
  command: grep -xq 'ExecStart=-/bin/sh -c "*/sbin/sulogin; /usr/bin/systemctl --fail --no-block default"' "{{ cis_sysconfig_rescue_filename }}"
  register: cis_rescue_1_4_3_output
  ignore_errors: True
  changed_when: False
  when: sysconfig_rescue_1_4_3 is defined and sysconfig_rescue_1_4_3.stat.exists
  tags:
    - level-1
    - "1.4.3"
    - scored

- name: '1.4.3 - Ensure authentication enabled for single user mode - emergency'
  command: grep -xq 'ExecStart=-/bin/sh -c "*/sbin/sulogin; /usr/bin/systemctl --fail --no-block default"' "{{ cis_sysconfig_emergency_filename }}"
  register: cis_emergency_1_4_3_output
  ignore_errors: True
  changed_when: False
  when: sysconfig_emergency_1_4_3 is defined and sysconfig_emergency_1_4_3.stat.exists
  tags:
    - level-1
    - "1.4.3"
    - scored

- name: 1.4.3 - Ensure authentication enabled for single user mode - {{ cis_sysconfig_rescue_filename }}
  lineinfile:
    dest: "{{ cis_sysconfig_rescue_filename }}"
    backup: yes
    regexp: "^ExecStart="
    insertafter: "^ExecStartPre=-/bin/echo"
    insertbefore: "^Type=idle"
    line: 'ExecStart=-/bin/sh -c "/usr/sbin/sulogin; /usr/bin/systemctl --fail --no-block default"'
  when: 
    - sysconfig_rescue_1_4_3 is defined and sysconfig_rescue_1_4_3.stat.exists
    - cis_rescue_1_4_3_output.rc != 0
  register: action_1_4_3_01
  tags:
    - level-1
    - "1.4.3"
    - scored


- name: 1.4.3 - Ensure authentication enabled for single user mode - {{ cis_sysconfig_emergency_filename }}
  lineinfile:
    dest: "{{ cis_sysconfig_emergency_filename }}"
    backup: yes
    regexp: "^ExecStart="
    insertafter: "^ExecStartPre=-/bin/echo"
    insertbefore: "^Type=idle"
    line: 'ExecStart=-/bin/sh -c "/usr/sbin/sulogin; /usr/bin/systemctl --fail --no-block default"'
  when: 
    - cis_emergency_1_4_3_output is defined and sysconfig_emergency_1_4_3.stat.exists
    - cis_emergency_1_4_3_output.rc != 0
  register: action_1_4_3_02
  tags:
    - level-1
    - "1.4.3"
    - scored


- name: 1.4.3 - Ensure authentication enabled for single user mode - emergency
  replace:
    path: "{{ cis_sysconfig_emergency_filename }}"
    after: '^ExecStartPre=\-\/bin\/echo '
    before: '^Type=idle'
    regexp: '^ExecStart='
    replace: 'ExecStart=-/bin/sh -c "/usr/sbin/sulogin; /usr/bin/systemctl --fail --no-block default"'
  when: 
    - cis_emergency_1_4_3_output is defined and sysconfig_rescue_1_4_3.stat.exists
    - cis_emergency_1_4_3_output.rc != 0
  register: action_1_4_3_02
  tags:
    - level-1
    - "1.4.3"
    - scored

- name: 1.4.3 - Logging action on {{ cis_sysconfig_rescue_filename }}
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.4.1 : insert /sbin/sulogin {{ cis_sysconfig_rescue_filename }}"
  when: action_1_4_3_01 is defined and action_1_4_3_01.changed  
  tags:
    - level-1
    - "1.4.3"
    - scored

- name: 1.4.3 - Logging action on {{ cis_sysconfig_emergency_filename }}
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.4.1 : insert /sbin/sulogin {{ cis_sysconfig_emergency_filename }}"
  when: action_1_4_3_02 is defined and action_1_4_3_02.changed  
  tags:
    - level-1
    - "1.4.3"
    - scored
