# Standards: 2.1.0
---

- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "2.3.3"
    - scored

# 2.3.3 Ensure talk client is not installed

- name: 2.3.3 - Ensure talk client is not installed
  yum:
    name: "talk"
    state: absent
  register: action_2_3_3
  tags:
    - level-1
    - "2.3.3"
    - scored

- name: 2.3.3 - Logging action 'yum remove talk'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 2.3.3 : Execute 'yum remove talk'"
  when: action_2_3_3 is defined and action_2_3_3.changed
  tags:
    - level-1
    - "2.3.3"
    - scored