# Standards: 2.1.0
---

- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "2.3.4"
    - scored

# 2.3.4 Ensure telnet client is not installed

- name: 2.3.4 - Ensure telnet client is not installed
  yum:
    name: "telnet"
    state: absent
  register: action_2_3_4
  tags:
    - level-1
    - section-2
    - "2.3.4"
    - scored

- name: 2.3.4 - Logging action 'yum remove telnet'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 2.3.4 : Execute 'yum remove telnet'"
  when: action_2_3_4 is defined and action_2_3_4.changed
  tags:
    - level-1
    - "2.3.4"
    - scored