# Standards: 2.1.0
---

- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "2.3.1"
    - scored

# 2.3.1 Ensure NIS Client is not installed

- name: 2.3.1 - Ensure NIS Client is not installed
  yum:
    name: "ypbind"
    state: absent
  register: action_2_3_1
  tags:
    - level-1
    - section-2
    - "2.3.1"
    - scored

- name: 2.3.1 - Logging action 'yum remove ypbind'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 2.3.1 : Execute 'yum remove ypbind'"
  when: action_2_3_1 is defined and action_2_3_1.changed
  tags:
    - level-1
    - "2.3.1"
    - scored