# Standards: 2.1.0
---

# 2.3.2 Ensure rsh client is not installed

- name: 2.3.2 - Ensure rsh client is not installed
  yum:
    name: "rsh"
    state: absent
  tags:
    - level-1
    - section-2
    - "2.3.2"
    - scored
