# Standards: 2.1.0
---
# 3.2.4 - Ensure ICMP redirects are not accepted (Scored)

- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "3.2.4"
    - scored

- name: 3.2.4 - Ensure ICMP redirects are not accepted and updated in the active kernel too
  sysctl:
    name: "{{ item }}"
    ignoreerrors: yes
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  with_items: "{{ cis_3_2_4_files }}"
  register: action_3_2_4
  notify: Flush ipv4 route
  tags:
    - level-1
    - section-3
    - "3.2.4"
    - scored

- name: 3.2.4 - Logging action 'Ensure ICMP redirects are not accepted and updated in the active kernel too'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 3.2.4 : Execute 'sysctl -w {{ item }} = 1'"
  with_items: "{{ cis_3_2_4_files }}"
  when: action_3_2_4 is defined and action_3_2_4.changed
  tags:
    - level-1
    - "3.2.4"
    - scored