# Standards: 2.1.0
---

# 4.2.3 Ensure rsyslog or syslog-ng is installed
# This module needs EPEL repo to be enabled. We will have to test this 
# in OMCS, FED and OCI. OCI it is enabled. 


- name: 4.2.3 - Ensure rsyslog is installed
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  when: cis_enable_rsyslog and not cis_enable_syslog_ng
  with_items:
    - { name: "rsyslog", state: "present" }
    - { name: "syslog-ng", state: "absent" }
  tags:
    - level-1
    - section-4
    - "4.2.3"
    - scored

- name: 4.2.3 - Ensure syslog-ng is installed
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enablerepo: epel
  when: cis_enable_syslog_ng and not cis_enable_rsyslog
  with_items:
    - { name: "rsyslog", state: "absent" }
    - { name: "syslog-ng", state: "present" }
  tags:
    - level-1
    - section-4
    - "4.2.3"
    - scored
