# Standards: 2.1.0
---

# 5.1.4 Ensure permissions on /etc/cron.daily are configured
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "5.1.4"
    - scored

- name: 5.1.4 - Ensure permissions on /etc/cron.daily are configured
  file:
    path: "/etc/cron.daily"
    owner: root
    group: root
    mode: '0600'
  register: action_5_1_4
  tags:
    - level-1
    - section-5
    - "5.1.4"
    - scored

- name: 5.1.4 - Logging Task 'Ensure permissions on /etc/cron.daily are configured'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 5.1.4 : chown root:root /etc/cron.daily && chmod og-rwx /etc/cron.daily"
  when: action_5_1_4 is defined and action_5_1_4.changed 
  tags:
    - level-1
    - section-1
    - "5.1.4"
    - scored