# Standards: 2.1.0
---

# 5.1.3 Ensure permissions on /etc/cron.hourly are configured
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "5.1.3"
    - scored

- name: 5.1.3 - Ensure permissions on /etc/cron.hourly are configured
  file:
    path: "/etc/cron.hourly"
    owner: root
    group: root
    mode: '0600'
  register: action_5_1_3
  tags:
    - level-1
    - section-5
    - "5.1.3"
    - scored

- name: 5.1.3 - Logging Task 'Ensure permissions on /etc/cron.hourly are configured'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 5.1.3 : chown root:root /etc/cron.hourly && chmod og-rwx /etc/cron.hourly"
  when: action_5_1_3 is defined and action_5_1_3.changed 
  tags:
    - level-1
    - section-1
    - "5.1.3"
    - scored