# Standards: 2.1.0
---

# 5.2.6 - Ensure SSH IgnoreRhosts is enabled
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "5.2.6"
    - scored

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.6"
    - scored

- name: 5.2.6 - Ensure SSH IgnoreRhosts is enabled
  lineinfile:
    regexp: "^IgnoreRhosts\\s+"
    backup: yes
    line: "IgnoreRhosts yes"
    dest: "/etc/ssh/sshd_config"
    insertbefore: "^#IgnoreRhosts"
  when: sshd_config.stat.exists
  register: action_5_2_6
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.6"
    - scored

- name: 5.2.6 - Logging Task 'Ensure SSH IgnoreRhosts is enabled'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 5.2.6 : 'IgnoreRhosts yes' -> /etc/ssh/sshd_config"
  when: action_5_2_6 is defined and action_5_2_6.changed 
  tags:
    - level-1
    - section-1
    - "5.2.6"
    - scored