# Standards: 2.1.0
---

# 5.2.13 - Ensure SSH LoginGraceTime is set to one minute or less (Scored)

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.13"
    - scored

- name: 5.2.13 - Ensure SSH Client Alive Interval is configured
  lineinfile:
    regexp: "^LoginGraceTime\\s+"
    line: "LoginGraceTime {{ cis_sshd_login_grace_time }}"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.13"
    - scored