# Standards: 2.1.0
---

# 5.2.3 - Ensure SSH LogLevel is set to INFO
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "5.2.3"
    - scored


- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.3"
    - scored

- name: 5.2.3 - Ensure SSH LogLevel is set to INFO
  lineinfile:
    regexp: "^LogLevel\\s+"
    line: "LogLevel INFO"
    dest: "/etc/ssh/sshd_config"
    backup: yes
    insertbefore: "^#LogLevel"
  when: sshd_config.stat.exists
  register: action_5_2_3
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.3"
    - scored

- name: 5.2.3 - Logging Task 'Ensure SSH LogLevel is set to INFO'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 5.2.3 : 'Ensure SSH LogLevel is set to INFO'"
  when: action_5_2_3 is defined and action_5_2_3.changed 
  tags:
    - level-1
    - section-1
    - "5.2.3"
    - scored
