# Standards: 2.1.0
---
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "6.1.3"
    - scored

# 6.1.3 Ensure permissions on /etc/shadow are configured

- name: 6.1.3 - Ensure permissions on /etc/shadow are configured
  file:
    path: /etc/shadow
    owner: root
    group: root
    mode: '0000'
  register: action_6_1_3
  tags:
    - level-1
    - section-6
    - "6.1.3"
    - scored

- name: '6.1.3 - Logging action - Ensure permissions on /etc/shadow are configured'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 6.1.3 : 'chown root:root /etc/shadow && chmod 000 /etc/shadow'"
  when: action_6_1_3 is defined and action_6_1_3.changed
  
  tags:
    - level-1
    - "6.1.3"
    - scored