# Standards: 2.1.0
---
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "6.1.6"
    - scored

# 6.1.6 Ensure permissions on /etc/passwd- are configured

- name: 6.1.6 - Discover permissions on /etc/passwd- (as Ansible cannot file it)
  stat:
    path: "/etc/passwd-"
  register: cis_st
  tags:
    - level-1
    - section-6
    - "6.1.6"
    - scored

- name: 6.1.6 - Display the file /etc/passd- mode
  debug:
    msg: The file mode is {{ cis_st.stat.mode }} expecting 0600
  tags:
    - level-1
    - section-6
    - "6.1.6"
    - scored

- name: 6.1.6 - Ensure permissions on /etc/passwd- are configured
  file:
    path: "/etc/passwd-"
    owner: root
    group: root
    mode: '0644'
  when: cis_st.stat.mode != 0600
  register: action_6_1_6
  tags:
    - level-1
    - section-6
    - "6.1.6"
    - scored

- name: '6.1.6 - Logging action - Ensure permissions on /etc/passwd- are configured'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 6.1.6 : 'chown root:root /etc/passwd- && chmod u-x,go-wx /etc/passwd'"
  when: action_6_1_6 is defined and action_6_1_6.changed
  
  tags:
    - level-1
    - "6.1.6"
    - scored