# Standards: 2.1.0
---
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "6.1.2"
    - scored

# 6.1.2 Ensure permissions on /etc/passwd are configured

- name: 6.1.2 - Ensure permissions on /etc/passwd are configured
  file:
    path: /etc/passwd
    owner: root
    group: root
    mode: '0644'
  register: action_6_1_2
  tags:
    - level-1
    - section-6
    - "6.1.2"
    - scored

- name: '6.1.2 - Logging action - Ensure permissions on /etc/passwd are configured'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 6.1.2 : 'chown root:root /etc/passwd && chmod 644 /etc/passwd'"
  when: action_6_1_2 is defined and action_6_1_2.changed
  
  tags:
    - level-1
    - "6.1.2"
    - scored