# Standards: 1.1.27
---

# 4.1.2 Ensure auditd Service is enabled

- name: 4.1.2 - Check if auditd is installed
  yum:
    name: audit
    state: present
  tags:
    - level-2
    - section-4
    - "4.1.2"
    - scored
    - skip_ansible_lint

- name: 4.1.2 - Ensure auditd Service is enabled
  service:
    name: "auditd"
    enabled: true
    state: started
  when:
  ignore_errors: false
  tags:
    - level-2
    - section-4
    - "4.1.2"
    - scored
